[package]
name = "lapce"
version = "0.11.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
lapce-plugin = "0.1.2"
serde = { version = "1.0.190", features = ["derive"] }
serde_json = "1.0.108"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true
