name: Checks

on:
  workflow_dispatch:
  pull_request:

jobs:
  rust:
    runs-on: ubuntu-latest
    name: Rust
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      
      - name: Tests
        run: cargo test
      
      - name: Clippy
        run: cargo clippy --all-targets --all-features -- -Dwarnings
      
      - name: Formatting
        run: cargo fmt --all -- --check
  
  cargo-deny:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: EmbarkStudios/cargo-deny-action@v1
  
  vs-code-extension:
    runs-on: ubuntu-latest
    name: VS Code Extension
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - run: npm install
        working-directory: ./addons/vscode
      
      - name: Compilation
        run: npm run compile
        working-directory: ./addons/vscode
      
      - name: Type Checking
        run: npm run check
        working-directory: ./addons/vscode
      
      - name: Tests
        run: npm run test
        working-directory: ./addons/vscode
      
      - name: Linting and Formatting
        run: |
          npm run lint
          npm run format-check
        working-directory: ./addons/vscode

      - name: Packaging
        # raises an error with packaging issues, eg. `@types/vscode` out of sync
        # with `engines.vscode`
        run: npx vsce ls
        working-directory: ./addons/vscode
