name: Checks

on:
  workflow_dispatch:
  pull_request:

jobs:
  language-server:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    name: Language Server ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2

      - name: Tests (default features)
        run: cargo test --no-fail-fast

      - name: Clippy (default features)
        run: cargo clippy --all-targets -- -Dwarnings

      - name: Tests (no default features)
        run: cargo test --no-fail-fast --no-default-features

      - name: Clippy (no default features)
        run: cargo clippy --all-targets --no-default-features -- -Dwarnings

      - name: Tests (native-tls)
        run: cargo test --no-fail-fast --no-default-features -F remote-packages,fontconfig,native-tls

      - name: Clippy (native-tls)
        run: cargo clippy --all-targets --no-default-features -F remote-packages,fontconfig,native-tls -- -Dwarnings

      - name: Formatting
        run: cargo fmt --all --check

  cargo-deny:
    name: Cargo Deny
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: EmbarkStudios/cargo-deny-action@v1

  vs-code-extension:
    name: VS Code Extension
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./editors/vscode

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - run: npm install

      - name: Compilation
        run: npm run compile

      - name: Type Checking
        run: npm run check

      - name: Tests
        run: npm run test

      - name: Linting and Formatting
        run: |
          npm run lint
          npm run format-check

      - name: Packaging
        # raises an error with packaging issues, eg. `@types/vscode` out of sync
        # with `engines.vscode`
        run: npx vsce ls
  
  lapce-extension:
    name: Lapce Extension
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./editors/lapce

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-wasi
      - uses: Swatinem/rust-cache@v2
      - uses: davidB/rust-cargo-make@v1.9.0

      - name: Check
        run: cargo make lapce-extension-check-flow
