name: Checks

on:
  workflow_dispatch:
  pull_request:

jobs:
  rust:
    runs-on: ubuntu-latest
    name: Rust
    steps:
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - uses: actions/checkout@v3
      
      - name: Tests
        run: cargo test

      - name: Clippy
        run: cargo clippy
      
      - name: Formatting
        run: cargo fmt --all -- --check
